version: '3'
services:
    apache:
        build: ./build/apache
        container_name: sf4_apache
        ports:
          - 8003:80
        volumes:
          - ./build/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/sf4
        depends_on:
          - php

    php:
        build: ./build/php
        container_name: sf4_php
        volumes:
          - .:/home/wwwroot/sf4